repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.16.4
  hooks:
  - id: gitleaks
    name: Gitleaks
    description: Detect hardcoded secrets
    entry: gitleaks detect --source . --verbose
    language: system
    pass_filenames: false
